import { Mail, Save, Search } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { fetchAdminCustomers, saveAdminCustomer, type AdminCustomer } from '../../src/api/admin';
import { formatCurrency } from '../../src/data/pricing';

export function AdminCustomers({ csrfToken }: { csrfToken: string }) {
  const [items, setItems] = useState<AdminCustomer[]>([]);
  const [selectedEmail, setSelectedEmail] = useState('');
  const [query, setQuery] = useState('');
  const [draft, setDraft] = useState<AdminCustomer>();
  const [tags, setTags] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { void fetchAdminCustomers().then((customers) => { setItems(customers); if (customers[0]) select(customers[0]); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to load customers')); }, []);
  const filtered = useMemo(() => items.filter((item) => `${item.name} ${item.email} ${item.organisation}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const select = (customer: AdminCustomer) => { setSelectedEmail(customer.email); setDraft(customer); setTags(customer.tags.join(', ')); };
  const save = async () => { if (!draft) return; try { const saved = await saveAdminCustomer(csrfToken, { ...draft, tags: tags.split(',').map((tag) => tag.trim()).filter(Boolean) }); const merged = { ...draft, ...saved }; setItems((current) => current.map((item) => item.email === merged.email ? merged : item)); select(merged); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save customer'); } };
  return <div className="admin-workspace-split"><section className="admin-panel admin-workspace-list"><label className="admin-search"><Search size={16} /><input onChange={(event) => setQuery(event.target.value)} placeholder="Search customers" value={query} /></label>{filtered.map((customer) => <button className={selectedEmail === customer.email ? 'is-active' : ''} key={customer.email} onClick={() => select(customer)} type="button"><strong>{customer.name || customer.email}</strong><small>{customer.organisation || customer.email}</small></button>)}{filtered.length === 0 ? <p className="admin-empty">No customers found.</p> : null}</section>{draft ? <section className="admin-panel admin-workspace-editor"><div className="admin-customer-heading"><span className="admin-account-avatar">{(draft.name || draft.email).charAt(0).toUpperCase()}</span><div><h2>{draft.name || draft.email}</h2><a href={`mailto:${draft.email}`}><Mail size={14} /> {draft.email}</a></div></div>{error ? <div className="alert alert-danger">{error}</div> : null}<div className="admin-management-grid"><label>Name<input className="form-control" onChange={(event) => setDraft({ ...draft, name: event.target.value })} value={draft.name} /></label><label>Organisation<input className="form-control" onChange={(event) => setDraft({ ...draft, organisation: event.target.value })} value={draft.organisation} /></label><label>Phone<input className="form-control" onChange={(event) => setDraft({ ...draft, phone: event.target.value })} value={draft.phone} /></label><label>Tags<input className="form-control" onChange={(event) => setTags(event.target.value)} value={tags} /></label></div><label>Customer notes<textarea className="form-control" onChange={(event) => setDraft({ ...draft, notes: event.target.value })} rows={5} value={draft.notes} /></label><button className="btn btn-accent" onClick={() => void save()} type="button"><Save size={16} /> Save profile</button><section className="admin-customer-history"><h3>Enquiries</h3>{draft.enquiries.map((item) => <article key={item.id}><span>{item.project_type || item.type}</span><small>{item.status} · {formatCurrency(item.estimated_cost)}</small></article>)}{draft.enquiries.length === 0 ? <p className="admin-empty">No enquiries.</p> : null}<h3>Projects</h3>{draft.projects.map((item) => <article key={item.id}><span>{item.name}</span><small>{item.stage} · {formatCurrency(item.value)} · {item.completion ?? 0}%</small></article>)}{draft.projects.length === 0 ? <p className="admin-empty">No projects.</p> : null}</section></section> : <section className="admin-panel admin-zero-state"><h2>No customer selected</h2></section>}</div>;
}
