import { Save } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { fetchAdminServices, saveAdminService, type AdminServiceOverride } from '../../src/api/admin';
import { pricingCategories } from '../../src/data/pricing';

const baseline = pricingCategories.flatMap((audience) => audience.groups.flatMap((group) => group.services.map((service, index) => ({ slug: service.slug, name: service.name, audience: audience.category, category: group.subcategory, description: group.description, best_for: service.bestFor, starting_from: service.startingFrom ?? 0, hourly_rate: service.hourlyRate ?? 0, estimated_hours: service.estimatedHours, deposit: service.deposit, active: true, sort_order: index }))));

export function AdminServices({ csrfToken }: { csrfToken: string }) {
  const [overrides, setOverrides] = useState<AdminServiceOverride[]>([]);
  const [selectedSlug, setSelectedSlug] = useState(baseline[0]?.slug ?? '');
  const [draft, setDraft] = useState<Partial<AdminServiceOverride>>(baseline[0]);
  const [error, setError] = useState('');
  useEffect(() => { void fetchAdminServices().then(setOverrides).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to load services')); }, []);
  const services = useMemo(() => baseline.map((service) => ({ ...service, ...overrides.find((item) => item.slug === service.slug) })), [overrides]);
  const select = (slug: string) => { const service = services.find((item) => item.slug === slug); if (service) { setSelectedSlug(slug); setDraft(service); } };
  const save = async () => { try { const saved = await saveAdminService(csrfToken, draft); setOverrides((current) => current.some((item) => item.slug === saved.slug) ? current.map((item) => item.slug === saved.slug ? saved : item) : [...current, saved]); setDraft(saved); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save service'); } };
  return <div className="admin-workspace-split"><section className="admin-panel admin-workspace-list">{services.map((service) => <button className={selectedSlug === service.slug ? 'is-active' : ''} key={service.slug} onClick={() => select(service.slug)} type="button"><strong>{service.name}</strong><small>{service.audience} · {service.category}</small></button>)}</section><section className="admin-panel admin-workspace-editor"><div className="admin-panel-heading"><div><h2>Edit service</h2><p>Saved values override the public pricing and quote catalogue.</p></div></div>{error ? <div className="alert alert-danger">{error}</div> : null}<div className="admin-management-grid"><label>Name<input className="form-control" onChange={(event) => setDraft({ ...draft, name: event.target.value })} value={draft.name ?? ''} /></label><label>Category<input className="form-control" onChange={(event) => setDraft({ ...draft, category: event.target.value })} value={draft.category ?? ''} /></label><label>Starting from (£)<input className="form-control" min="0" onChange={(event) => setDraft({ ...draft, starting_from: Number(event.target.value) })} type="number" value={draft.starting_from ?? 0} /></label><label>Hourly rate (£)<input className="form-control" min="0" onChange={(event) => setDraft({ ...draft, hourly_rate: Number(event.target.value) })} step="0.01" type="number" value={draft.hourly_rate ?? 0} /></label><label>Estimated hours<input className="form-control" min="0" onChange={(event) => setDraft({ ...draft, estimated_hours: Number(event.target.value) })} type="number" value={draft.estimated_hours ?? 0} /></label><label>Deposit<input className="form-control" onChange={(event) => setDraft({ ...draft, deposit: event.target.value })} value={draft.deposit ?? ''} /></label></div><label>Best for<textarea className="form-control" onChange={(event) => setDraft({ ...draft, best_for: event.target.value })} rows={3} value={draft.best_for ?? ''} /></label><label className="admin-archive-toggle"><input checked={draft.active !== false} onChange={(event) => setDraft({ ...draft, active: event.target.checked })} type="checkbox" /> Active on public pages</label><button className="btn btn-accent" onClick={() => void save()} type="button"><Save size={16} /> Save service</button></section></div>;
}
